# Device Name
device_name: "DIGIT: DIGIT"
# device_name: "GelSight Mini R0B 2DA7-P1FZ: Ge"
# Pixel Per Millimeter
mmpp: 0.0634
# Image Width and Height
h: 240
w: 320
# Pressing depth in m
press_depth: 0.001

# All the number has no concern in terms of axis
# length of 3D printed mount in milimeter
mount_length: 75
# length of gelsight sensor itself ex. gel
gs_length: 24.25
gel_thickness: 4

# the sensor's center is not exactly the centor of the mount
x_offset: 0.25
y_offset: 0.5
